local_backend: true

media_folder: "static/images/uploads"
backend:
  name: github
  branch: digthedill/portfolio
collections:
  - label: Blog
    name: "blog"
    folder: "src/posts"
    create: true
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      